security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
   encoders:
        App\Entity\User: auto
   
   providers:
         in_database:
            entity:
                class: App\Entity\User
                property: username
   firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: in_database
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path:  true
                default_target_path:  /
            logout:
                path: logout
                target: /           

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
   access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tasks/create, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: ROLE_USER }


    
        